# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrcaCli < Formula
  desc ""
  homepage ""
  version "1.0.0-LJ12"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/orcasecurity/orca-cli/releases/download/1.0.0-LJ12/orca-cli_1.0.0-LJ12_darwin_arm64.tar.gz"
      sha256 "dbcd14f030e1b4445e9ec9a7a4b645ab2d44e0bba53257573d89b41d46a60549"

      def install
        bin.install "orca-cli"
      end
    end
  end
end
